export interface Country {
  name: string;
  code: string;
  currency: string;
  currencySymbol: string;
}

export const countries: Country[] = [
  { name: "United States", code: "US", currency: "USD", currencySymbol: "$" },
  { name: "United Kingdom", code: "GB", currency: "GBP", currencySymbol: "£" },
  { name: "Canada", code: "CA", currency: "CAD", currencySymbol: "$" },
  { name: "Australia", code: "AU", currency: "AUD", currencySymbol: "$" },
  { name: "Germany", code: "DE", currency: "EUR", currencySymbol: "€" },
  { name: "France", code: "FR", currency: "EUR", currencySymbol: "€" },
  { name: "Italy", code: "IT", currency: "EUR", currencySymbol: "€" },
  { name: "Spain", code: "ES", currency: "EUR", currencySymbol: "€" },
  { name: "Netherlands", code: "NL", currency: "EUR", currencySymbol: "€" },
  { name: "Belgium", code: "BE", currency: "EUR", currencySymbol: "€" },
  { name: "Switzerland", code: "CH", currency: "CHF", currencySymbol: "Fr" },
  { name: "Sweden", code: "SE", currency: "SEK", currencySymbol: "kr" },
  { name: "Norway", code: "NO", currency: "NOK", currencySymbol: "kr" },
  { name: "Denmark", code: "DK", currency: "DKK", currencySymbol: "kr" },
  { name: "Japan", code: "JP", currency: "JPY", currencySymbol: "¥" },
  { name: "China", code: "CN", currency: "CNY", currencySymbol: "¥" },
  { name: "India", code: "IN", currency: "INR", currencySymbol: "₹" },
  { name: "Singapore", code: "SG", currency: "SGD", currencySymbol: "$" },
  { name: "Hong Kong", code: "HK", currency: "HKD", currencySymbol: "$" },
  { name: "South Korea", code: "KR", currency: "KRW", currencySymbol: "₩" },
  { name: "Brazil", code: "BR", currency: "BRL", currencySymbol: "R$" },
  { name: "Mexico", code: "MX", currency: "MXN", currencySymbol: "$" },
  { name: "Argentina", code: "AR", currency: "ARS", currencySymbol: "$" },
  { name: "Chile", code: "CL", currency: "CLP", currencySymbol: "$" },
  { name: "Colombia", code: "CO", currency: "COP", currencySymbol: "$" },
  { name: "South Africa", code: "ZA", currency: "ZAR", currencySymbol: "R" },
  { name: "Nigeria", code: "NG", currency: "NGN", currencySymbol: "₦" },
  { name: "Kenya", code: "KE", currency: "KES", currencySymbol: "KSh" },
  { name: "Egypt", code: "EG", currency: "EGP", currencySymbol: "£" },
  { name: "UAE", code: "AE", currency: "AED", currencySymbol: "د.إ" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", currencySymbol: "﷼" },
  { name: "Turkey", code: "TR", currency: "TRY", currencySymbol: "₺" },
  { name: "Russia", code: "RU", currency: "RUB", currencySymbol: "₽" },
  { name: "Poland", code: "PL", currency: "PLN", currencySymbol: "zł" },
  { name: "Czech Republic", code: "CZ", currency: "CZK", currencySymbol: "Kč" },
  { name: "Hungary", code: "HU", currency: "HUF", currencySymbol: "Ft" },
  { name: "Romania", code: "RO", currency: "RON", currencySymbol: "lei" },
  { name: "Greece", code: "GR", currency: "EUR", currencySymbol: "€" },
  { name: "Portugal", code: "PT", currency: "EUR", currencySymbol: "€" },
  { name: "Austria", code: "AT", currency: "EUR", currencySymbol: "€" },
  { name: "Ireland", code: "IE", currency: "EUR", currencySymbol: "€" },
  { name: "Finland", code: "FI", currency: "EUR", currencySymbol: "€" },
  { name: "New Zealand", code: "NZ", currency: "NZD", currencySymbol: "$" },
  { name: "Malaysia", code: "MY", currency: "MYR", currencySymbol: "RM" },
  { name: "Thailand", code: "TH", currency: "THB", currencySymbol: "฿" },
  { name: "Indonesia", code: "ID", currency: "IDR", currencySymbol: "Rp" },
  { name: "Philippines", code: "PH", currency: "PHP", currencySymbol: "₱" },
  { name: "Vietnam", code: "VN", currency: "VND", currencySymbol: "₫" },
  { name: "Pakistan", code: "PK", currency: "PKR", currencySymbol: "₨" },
  { name: "Bangladesh", code: "BD", currency: "BDT", currencySymbol: "৳" },
  { name: "Israel", code: "IL", currency: "ILS", currencySymbol: "₪" },
].sort((a, b) => a.name.localeCompare(b.name));
